/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tocadorMidi.interfaces;

import tocadorMidi.engine.actionListeners.BotaoPause;
import tocadorMidi.engine.actionListeners.BotaoPlay;
import tocadorMidi.engine.actionListeners.BotaoSkipBackward;
import tocadorMidi.engine.actionListeners.BotaoSkipForward;
import tocadorMidi.engine.actionListeners.BotaoStop;
import tocadorMidi.engine.actionListeners.SliderAudio;
import tocadorMidi.engine.actionListeners.SliderVolume;

/**
 *
 * @author mariana
 */
public class FrameTocador extends javax.swing.JFrame {

    /**
     * Creates new form FrameTocadoe
     */
    public FrameTocador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        labelFaixa = new javax.swing.JLabel();
        labelNomeDaFaixa = new javax.swing.JLabel();
        sliderAudio = new javax.swing.JSlider();
        tempoFaixa = new javax.swing.JLabel();
        botaoPlay = new javax.swing.JButton();
        botaoPause = new javax.swing.JButton();
        botaoStop = new javax.swing.JButton();
        botaoSkipBkwrd = new javax.swing.JButton();
        botaoSkipFwd = new javax.swing.JButton();
        sliderVolume = new javax.swing.JSlider();
        labelFormulaCompasso = new javax.swing.JLabel();
        labelMetro = new javax.swing.JLabel();
        labelAndamento = new javax.swing.JLabel();
        labelArmaduraTonalidade = new javax.swing.JLabel();
        labelValorCompasso = new javax.swing.JLabel();
        labelValorMetro = new javax.swing.JLabel();
        labelValorAndamento = new javax.swing.JLabel();
        labelValorTonalidade = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        itemImportarBanco = new javax.swing.JMenuItem();
        itemImportarArq = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelFaixa.setText("Faixa: ");

        labelNomeDaFaixa.setText("Nome_da_faixa.MIDI");
        labelNomeDaFaixa.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                labelNomeDaFaixaPropertyChange(evt);
            }
        });

        sliderAudio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sliderAudioMouseDragged(evt);
            }
        });
        sliderAudio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                sliderAudioPropertyChange(evt);
            }
        });

        tempoFaixa.setText("00:00:00");

        botaoPlay.setText("Play");
        botaoPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoPlayMouseClicked(evt);
            }
        });

        botaoPause.setText("Pause");
        botaoPause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoPauseMouseClicked(evt);
            }
        });

        botaoStop.setText("Stop");
        botaoStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoStopMouseClicked(evt);
            }
        });

        botaoSkipBkwrd.setText("<<");
        botaoSkipBkwrd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoSkipBkwrdMouseClicked(evt);
            }
        });

        botaoSkipFwd.setText(">>");
        botaoSkipFwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoSkipFwdMouseClicked(evt);
            }
        });

        sliderVolume.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sliderVolumeMouseDragged(evt);
            }
        });

        labelFormulaCompasso.setText("Formula de Compasso: ");

        labelMetro.setText("Metro: ");

        labelAndamento.setText("Andamento: ");

        labelArmaduraTonalidade.setText("Armadura de Tonalidade: ");

        labelValorCompasso.setText("compasso");
        labelValorCompasso.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                labelValorCompassoPropertyChange(evt);
            }
        });

        labelValorMetro.setText("metro");
        labelValorMetro.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                labelValorMetroPropertyChange(evt);
            }
        });

        labelValorAndamento.setText("andamento");

        labelValorTonalidade.setText("tonalidade");

        fileMenu.setText("File");

        itemImportarBanco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itemImportarBanco.setText("Importar Banco MIDI...");
        itemImportarBanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemImportarBancoMouseClicked(evt);
            }
        });
        fileMenu.add(itemImportarBanco);

        itemImportarArq.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itemImportarArq.setText("Importar Arq. MIDI...");
        itemImportarArq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemImportarArqMouseClicked(evt);
            }
        });
        fileMenu.add(itemImportarArq);

        barraMenu.add(fileMenu);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderAudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelFaixa)
                        .addGap(18, 18, 18)
                        .addComponent(labelNomeDaFaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tempoFaixa))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoPlay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoPause)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoStop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoSkipBkwrd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoSkipFwd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMetro)
                            .addComponent(labelAndamento)
                            .addComponent(labelArmaduraTonalidade)
                            .addComponent(labelFormulaCompasso))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(labelValorCompasso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelValorMetro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelValorAndamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelValorTonalidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFaixa)
                    .addComponent(labelNomeDaFaixa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderAudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tempoFaixa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botaoPlay)
                                .addComponent(botaoPause)
                                .addComponent(botaoStop)
                                .addComponent(botaoSkipBkwrd)
                                .addComponent(botaoSkipFwd))
                            .addComponent(sliderVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelFormulaCompasso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelMetro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelAndamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelArmaduraTonalidade))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelValorCompasso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelValorMetro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelValorAndamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelValorTonalidade)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelValorCompassoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_labelValorCompassoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_labelValorCompassoPropertyChange

    private void labelValorMetroPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_labelValorMetroPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_labelValorMetroPropertyChange

    private void labelNomeDaFaixaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_labelNomeDaFaixaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_labelNomeDaFaixaPropertyChange

    private void sliderAudioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_sliderAudioPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_sliderAudioPropertyChange

    private void itemImportarBancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemImportarBancoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_itemImportarBancoMouseClicked

    private void itemImportarArqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemImportarArqMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_itemImportarArqMouseClicked

    private void botaoPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoPlayMouseClicked
        BotaoPlay acao = new BotaoPlay();
    }//GEN-LAST:event_botaoPlayMouseClicked

    private void botaoPauseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoPauseMouseClicked
        BotaoPause acao = new BotaoPause();
    }//GEN-LAST:event_botaoPauseMouseClicked

    private void botaoStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoStopMouseClicked
        BotaoStop acao = new BotaoStop();
    }//GEN-LAST:event_botaoStopMouseClicked

    private void botaoSkipBkwrdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSkipBkwrdMouseClicked
        BotaoSkipBackward acao = new BotaoSkipBackward();
    }//GEN-LAST:event_botaoSkipBkwrdMouseClicked

    private void botaoSkipFwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSkipFwdMouseClicked
        BotaoSkipForward acao = new BotaoSkipForward();
    }//GEN-LAST:event_botaoSkipFwdMouseClicked

    private void sliderVolumeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderVolumeMouseDragged
        SliderVolume acao = new SliderVolume();
    }//GEN-LAST:event_sliderVolumeMouseDragged

    private void sliderAudioMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderAudioMouseDragged
        SliderAudio acao = new SliderAudio();
    }//GEN-LAST:event_sliderAudioMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botaoPause;
    private javax.swing.JButton botaoPlay;
    private javax.swing.JButton botaoSkipBkwrd;
    private javax.swing.JButton botaoSkipFwd;
    private javax.swing.JButton botaoStop;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem itemImportarArq;
    private javax.swing.JMenuItem itemImportarBanco;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel labelAndamento;
    private javax.swing.JLabel labelArmaduraTonalidade;
    private javax.swing.JLabel labelFaixa;
    private javax.swing.JLabel labelFormulaCompasso;
    private javax.swing.JLabel labelMetro;
    private javax.swing.JLabel labelNomeDaFaixa;
    private javax.swing.JLabel labelValorAndamento;
    private javax.swing.JLabel labelValorCompasso;
    private javax.swing.JLabel labelValorMetro;
    private javax.swing.JLabel labelValorTonalidade;
    private javax.swing.JSlider sliderAudio;
    private javax.swing.JSlider sliderVolume;
    private javax.swing.JLabel tempoFaixa;
    // End of variables declaration//GEN-END:variables
}
