/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tocadorMidi.interfaces;

import tocadorMidi.engine.actionListeners.BotaoPause;
import tocadorMidi.engine.actionListeners.BotaoPlay;
import tocadorMidi.engine.actionListeners.SliderAudio;

/**
 *
 * @author mariana
 */
public class JanelaTocador extends javax.swing.JPanel {

    /**
     * Creates new form JanelaTocador
     */
    public JanelaTocador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jInternalFrame1 = new javax.swing.JInternalFrame();
        labelFaixa = new javax.swing.JLabel();
        labelNomeDaFaixa = new javax.swing.JLabel();
        sliderAudio = new javax.swing.JSlider();
        posicaoFaixa = new javax.swing.JLabel();
        botaoPlay = new javax.swing.JButton();
        botaoPause = new javax.swing.JButton();
        botaoStop = new javax.swing.JButton();
        botaoSkipBackward = new javax.swing.JButton();
        botaoSkipForward = new javax.swing.JButton();
        sliderVolume = new javax.swing.JSlider();
        labelFormulaCompasso = new javax.swing.JLabel();
        labelMetro = new javax.swing.JLabel();
        labelAndamento = new javax.swing.JLabel();
        labelArmaduraTonalidade = new javax.swing.JLabel();
        labelValorCompasso = new javax.swing.JLabel();
        labelValorMetro = new javax.swing.JLabel();
        labelValorAndamento = new javax.swing.JLabel();
        labelValorTonalidade = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        selecionarBancoMidi = new javax.swing.JMenuItem();
        selecionarArqMidi = new javax.swing.JMenuItem();

        jInternalFrame1.setVisible(true);

        labelFaixa.setText("Faixa:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, sliderAudio, org.jdesktop.beansbinding.ELProperty.create("${value}"), sliderAudio, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        sliderAudio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sliderAudioMousePressed(evt);
            }
        });

        posicaoFaixa.setText("00:00:00");

        botaoPlay.setText("Play");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, botaoPlay, org.jdesktop.beansbinding.ELProperty.create("${}"), botaoPlay, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        botaoPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoPlayMouseClicked(evt);
            }
        });

        botaoPause.setText("Pause");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, botaoPause, org.jdesktop.beansbinding.ObjectProperty.create(), botaoPause, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        botaoPause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoPauseMouseClicked(evt);
            }
        });

        botaoStop.setText("Stop");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, botaoStop, org.jdesktop.beansbinding.ObjectProperty.create(), botaoStop, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        botaoSkipBackward.setText("<<");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, botaoSkipBackward, org.jdesktop.beansbinding.ObjectProperty.create(), botaoSkipBackward, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        botaoSkipForward.setText(">>");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, botaoSkipForward, org.jdesktop.beansbinding.ObjectProperty.create(), botaoSkipForward, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, sliderVolume, org.jdesktop.beansbinding.ObjectProperty.create(), sliderVolume, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        labelFormulaCompasso.setText("Formula de Compasso: ");

        labelMetro.setText("Metro: ");

        labelAndamento.setText("Andamento: ");

        labelArmaduraTonalidade.setText("Armadura de Tonalidade: ");

        labelValorCompasso.setText("compasso");

        labelValorMetro.setText("metro");
        labelValorMetro.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                labelValorMetroPropertyChange(evt);
            }
        });

        labelValorAndamento.setText("andamento");

        labelValorTonalidade.setText("tonalidade");

        jMenu1.setText("File");

        selecionarBancoMidi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        selecionarBancoMidi.setText("Selecionar Banco...");
        selecionarBancoMidi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecionarBancoMidiMouseClicked(evt);
            }
        });
        jMenu1.add(selecionarBancoMidi);

        selecionarArqMidi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        selecionarArqMidi.setText("Selecionar Arq. MIDI...");
        selecionarArqMidi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecionarArqMidiMouseClicked(evt);
            }
        });
        jMenu1.add(selecionarArqMidi);

        jMenuBar1.add(jMenu1);

        jInternalFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderAudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(labelFaixa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNomeDaFaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(posicaoFaixa))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelMetro)
                                    .addComponent(labelAndamento)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                .addComponent(botaoPlay)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(botaoPause))
                                            .addComponent(labelFormulaCompasso))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                .addComponent(botaoStop)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(botaoSkipBackward)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(botaoSkipForward)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(sliderVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(labelValorCompasso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelValorMetro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelValorAndamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 5, Short.MAX_VALUE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(labelArmaduraTonalidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelValorTonalidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelFaixa)
                            .addComponent(labelNomeDaFaixa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderAudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(posicaoFaixa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoPlay)
                            .addComponent(botaoPause)
                            .addComponent(botaoStop)
                            .addComponent(botaoSkipBackward)
                            .addComponent(botaoSkipForward)))
                    .addComponent(sliderVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFormulaCompasso)
                    .addComponent(labelValorCompasso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetro)
                    .addComponent(labelValorMetro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAndamento)
                    .addComponent(labelValorAndamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelArmaduraTonalidade)
                    .addComponent(labelValorTonalidade))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void sliderAudioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderAudioMousePressed
        SliderAudio acao = new SliderAudio();
    }//GEN-LAST:event_sliderAudioMousePressed

    private void botaoPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoPlayMouseClicked
        BotaoPlay acao = new BotaoPlay();
    }//GEN-LAST:event_botaoPlayMouseClicked

    private void selecionarBancoMidiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecionarBancoMidiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_selecionarBancoMidiMouseClicked

    private void selecionarArqMidiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecionarArqMidiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_selecionarArqMidiMouseClicked

    private void botaoPauseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoPauseMouseClicked
        BotaoPause acao = new BotaoPause();
    }//GEN-LAST:event_botaoPauseMouseClicked

    private void labelValorMetroPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_labelValorMetroPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_labelValorMetroPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoPause;
    private javax.swing.JButton botaoPlay;
    private javax.swing.JButton botaoSkipBackward;
    private javax.swing.JButton botaoSkipForward;
    private javax.swing.JButton botaoStop;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelAndamento;
    private javax.swing.JLabel labelArmaduraTonalidade;
    private javax.swing.JLabel labelFaixa;
    private javax.swing.JLabel labelFormulaCompasso;
    private javax.swing.JLabel labelMetro;
    private javax.swing.JLabel labelNomeDaFaixa;
    private javax.swing.JLabel labelValorAndamento;
    private javax.swing.JLabel labelValorCompasso;
    private javax.swing.JLabel labelValorMetro;
    private javax.swing.JLabel labelValorTonalidade;
    private javax.swing.JLabel posicaoFaixa;
    private javax.swing.JMenuItem selecionarArqMidi;
    private javax.swing.JMenuItem selecionarBancoMidi;
    private javax.swing.JSlider sliderAudio;
    private javax.swing.JSlider sliderVolume;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
